/** @type {import('next').NextConfig} */
const nextConfig = {
	images: {
		remotePatterns: [
			{
				protocol: 'https',
				hostname: 'cdn.sanity.io',
				port: '',
			},
			{
				protocol: 'https',
				hostname: '*.googleusercontent.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'pbs.twimg.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'plus.unsplash.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'images.unsplash.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'm.media-amazon.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'thumbs.wbm.im',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'www.fsis.usda.gov',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'www.shoesforcrews.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'z.dam-img.rfdcontent.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'www.cdc.gov',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'www.cdph.ca.gov',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'media.licdn.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'cdn.cms-twdigitalassets.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'developers.google.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'i.sstatic.net',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'cloud.githubusercontent.com',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 't3.ftcdn.net',
				port: '',
				pathname: '**',
			},
			{
				protocol: 'https',
				hostname: 'images.pexels.com',
				port: '',
				pathname: '**',
			},
		],
		// domains: ['lh3.googleusercontent.com'],
		// domains: ['pbs.twing.com'],
		// domains: ['images.unsplash.com'],
		// domains: ['thumbs.wbm.im'],
		// domains: ['www.fsis.usda.gov'],
		// domains: ['www.shoesforcrews.com'],
		// domains: ['z.dam-img.rfdcontent.com'],
		// domains: ['www.cdc.gov'],
		// domains: ['www.cdph.ca.gov'],
		// domains: ['www.media.licdn.com'],
		// domains: ['cdn.cms-twdigitalassets.com'],
		// domains: ['developers.google.com'],
		// domains: ['i.sstatic.net'],
		// domains: ['cloud.githubusercontent.com'],
		// domains: ['t3.ftcdn.net'],
	},
};

export default nextConfig;
